FAKE NEWS DETECTION

DATA CLEANING

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
fake_df = pd.read_csv("1Fake.csv")
true_df = pd.read_csv("2True.csv")

In [3]:
fake_df.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [4]:
true_df.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

In [5]:
fake_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB


In [6]:
true_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB


In [7]:
fake_df["class"] = 0
true_df["class"] = 1

In [8]:
true_df.shape

(21417, 5)

In [20]:
fake_df.shape

(23481, 5)

In [9]:
manualtesting_df = pd.read_csv("4manual_testing.csv")

In [10]:
for i in range(23480,23470,-1):
    fake_df.drop([i],axis = 0, inplace = True)

for i in range(21416,21406,-1):
    true_df.drop([i],axis = 0, inplace = True)


In [23]:
manualtesting_df.head()

Unnamed: 0                                              title  \
0       23471  Seven Iranians freed in the prisoner swap have...   
1       23472                      #Hashtag Hell & The Fake Left   
2       23473  Astroturfing: Journalist Reveals Brainwashing ...   
3       23474          The New American Century: An Era of Fraud   
4       23475  Hillary Clinton: ‘Israel First’ (and no peace ...   

                                                text      subject  \
0  21st Century Wire says This week, the historic...  Middle-east   
1   By Dady Chery and Gilbert MercierAll writers ...  Middle-east   
2  Vic Bishop Waking TimesOur reality is carefull...  Middle-east   
3  Paul Craig RobertsIn the last years of the 20t...  Middle-east   
4  Robert Fantina CounterpunchAlthough the United...  Middle-east   

               date  class  
0  January 20, 2016      0  
1  January 19, 2016      0  
2  January 19, 2016      0  
3  January 19, 2016      0  
4  January 18, 2016      0

In [11]:
data_df = pd.concat([fake_df,true_df],axis=0)
data_df.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0  
5  December 25, 2017      0  
6  December 23, 2017      0  
7  December 23, 2017      0  
8  December 22, 2017      0  
9  December 21, 2017      0

In [12]:
data = data_df.drop(['title','subject','date'],axis=1)

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44878 entries, 0 to 21406
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    44878 non-null  object
 1   class   44878 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 1.0+ MB


In [13]:
data = data.sample(frac = 1)

In [28]:
data.head()

text  class
16081  EX-CIA Chief John Brennan testified today befo...      0
2533   After years of investigating Hillary Clinton o...      0
158    A Capitol Hill press conference that was suppo...      0
2880   BEIJING (Reuters) - Chinese President Xi Jinpi...      1
4839   This is so horribly amazing that it defies des...      0

In [14]:
data.reset_index(inplace=True)
data.drop(['index'],axis = 1,inplace =True)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44878 entries, 0 to 44877
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    44878 non-null  object
 1   class   44878 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 701.3+ KB


In [31]:
data

text  class
0      EX-CIA Chief John Brennan testified today befo...      0
1      After years of investigating Hillary Clinton o...      0
2      A Capitol Hill press conference that was suppo...      0
3      BEIJING (Reuters) - Chinese President Xi Jinpi...      1
4      This is so horribly amazing that it defies des...      0
...                                                  ...    ...
44873  WASHINGTON (Reuters) - Republican presidential...      1
44874  BEIJING (Reuters) - China defended its right o...      1
44875  LONDON (Reuters) - Legislation underpinning th...      1
44876  BEIRUT (Reuters) - The Syrian army and its all...      1
44877  COX S BAZAR/YANGON (Reuters) - Hungry, destitu...      1

[44878 rows x 2 columns]

DATA PREPROCESSING

Preprocessing text. removeing extra space,special chr,url and links and covert to lowercase

In [15]:
import re
import string
def wordopt(text):
    text = text.lower()  # convert to lowercase
    text = re.sub('\[.*?\]', '', text)  # remove text in brackets
    text = re.sub('https?://\S+|www\.\S+', '', text)  # remove URLs
    text = re.sub('<.*?>+', '', text)  # remove HTML tags
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)  # remove punctuation
    text = re.sub('\w*\d\w*', '', text)  # remove words containing numbers
    text = re.sub('\s+', ' ', text).strip()  # remove extra spaces
    text = re.sub("['\"“”‘’]", '', text)  # remove fancy/single/double quotes
    return text


<>:5: SyntaxWarning: invalid escape sequence '\['
<>:6: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
<>:10: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\['
<>:6: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
<>:10: SyntaxWarning: invalid escape sequence '\s'
C:\Users\DELL\AppData\Local\Temp\ipykernel_584\432605758.py:5: SyntaxWarning: invalid escape sequence '\['
  text = re.sub('\[.*?\]', '', text)  # remove text in brackets
C:\Users\DELL\AppData\Local\Temp\ipykernel_584\432605758.py:6: SyntaxWarning: invalid escape sequence '\S'
  text = re.sub('https?://\S+|www\.\S+', '', text)  # remove URLs
C:\Users\DELL\AppData\Local\Temp\ipykernel_584\432605758.py:9: SyntaxWarning: invalid escape sequence '\w'
  text = re.sub('\w*\d\w*', '', text)  # remove words containing numbers
C:\Users\DELL\AppData\Local\Temp\ipykernel_584\432605758.py:10: SyntaxWarn

In [16]:
data["text"] = data["text"].apply(wordopt)

In [38]:
data

text  class
0      ex cia chief john brennan testified today befo...      0
1      after years of investigating hillary clinton o...      0
2      a capitol hill press conference that was suppo...      0
3      beijing reuters chinese president xi jinping a...      1
4      this is so horribly amazing that it defies des...      0
...                                                  ...    ...
44873  washington reuters republican presidential can...      1
44874  beijing reuters china defended its right on th...      1
44875  london reuters legislation underpinning the go...      1
44876  beirut reuters the syrian army and its allies ...      1
44877  cox s bazar yangon reuters hungry destitute an...      1

[44878 rows x 2 columns]

FEATURE ENGINEERING

import nltk...
nltk.download('punkt')...
from nltk.tokenize import word_tokenize...
data["text] = data["text"].apply(word_tokenize)...
DIDN'T WORK

1. TOKENIZATION

In [17]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [18]:
data["tokens"] = data["text"].apply(lambda x: [token.text for token in nlp(x)])
#takes a lot of time

2. STOP WORD REMOVAL

In [19]:
from spacy.lang.en.stop_words import STOP_WORDS

In [20]:
def remove_stopwords(tokens):
    return [token for token in tokens if token.lower() not in STOP_WORDS]

data["tokens"] = data["tokens"].apply(remove_stopwords)

In [21]:
data.to_csv('cleanedData.csv',index=False)

In [ ]:
data = pd.read_csv("cleanedData.csv")

In [24]:
data

text  class  \
0      nairobi reuters kenya s opposition leader rail...      1   
1      washington reuters the obama administration on...      1   
2                                                             0   
3      funny how this just keeps happeningyet another...      0   
4      helsinki reuters any move by finland to join n...      1   
...                                                  ...    ...   
44873  a gop lobbyist who s known for his own brand o...      0   
44874  washington reuters us president donald trump o...      1   
44875  washington reuters us president donald trump i...      1   
44876  in september stephen henderson the editorial e...      0   
44877  as said last year the russian hacking or russi...      0   

                                                  tokens  
0      [nairobi, reuters, kenya, s, opposition, leade...  
1      [washington, reuters, obama, administration, t...  
2                                                     []  
3      [funny, keeps, happeningyet, trump, advisor, c...  
4      [helsinki, reuters, finland, join, nato, need,...  
...                                                  ...  
44873  [gop, lobbyist, s, known, brand, bigotry, deno...  
44874  [washington, reuters, president, donald, trump...  
44875  [washington, reuters, president, donald, trump...  
44876  [september, stephen, henderson, editorial, edi...  
44877  [said, year, russian, hacking, russiagate, sto...  

[44878 rows x 3 columns]

3. LEMMATIZATION

In [25]:
def lemmatize_tokens(tokens):
    doc = nlp(" ".join(tokens))  #convert list of tokens to a string
    return [token.lemma_ for token in doc]

data["tokens"] = data["tokens"].apply(lemmatize_tokens)

4. VECTORIZATION:- WORD TO VECTOR CONVERSION

USING Word2Vector 

In [26]:
from gensim.models import Word2Vec

In [27]:
sentences = data["tokens"].tolist()

In [28]:
model = Word2Vec(sentences= sentences,vector_size=100,window=5,min_count=2,workers=4)

In [29]:
model

In [46]:
model.wv["fake"]
model.wv.similarity("true","fake")  #returns cosine similarity score
model.wv.most_similar("truth")

[('lie', 0.6884638667106628),
 ('sadly', 0.5916675925254822),
 ('true', 0.5916601419448853),
 ('honest', 0.5884286165237427),
 ('fact', 0.5826237797737122),
 ('myth', 0.571536660194397),
 ('itthe', 0.5676210522651672),
 ('logic', 0.5665364861488342),
 ('falsehood', 0.5617994666099548),
 ('pure', 0.5536658763885498)]

In [47]:
model.save("word2vector.model")

5. Convert sentences to vectors:- word2vector gives word embeddings- but ML models need sentence/doc vectors.

In [49]:
def sentence_vector(tokens, model):
    vectors = [model.wv[word] for word in tokens if word in model.wv]
    return np.mean(vectors,axis=0) if vectors else np.zeros(model.vector_size)

In [50]:
data["vector"] = data["tokens"].apply(lambda x: sentence_vector(x,model))

In [52]:
data

text  class  \
0      nairobi reuters kenya s opposition leader rail...      1   
1      washington reuters the obama administration on...      1   
2                                                             0   
3      funny how this just keeps happeningyet another...      0   
4      helsinki reuters any move by finland to join n...      1   
...                                                  ...    ...   
44873  a gop lobbyist who s known for his own brand o...      0   
44874  washington reuters us president donald trump o...      1   
44875  washington reuters us president donald trump i...      1   
44876  in september stephen henderson the editorial e...      0   
44877  as said last year the russian hacking or russi...      0   

                                                  tokens  \
0      [nairobi, reuters, kenya, s, opposition, leade...   
1      [washington, reuters, obama, administration, t...   
2                                                     []   
3      [funny, keep, happeningyet, trump, advisor, ca...   
4      [helsinki, reuters, finland, join, nato, need,...   
...                                                  ...   
44873  [gop, lobbyist, s, know, brand, bigotry, denou...   
44874  [washington, reuters, president, donald, trump...   
44875  [washington, reuters, president, donald, trump...   
44876  [september, stephen, henderson, editorial, edi...   
44877  [say, year, russian, hack, russiagate, story, ...   

                                                  vector  
0      [-0.2608485, -0.3120744, -0.22567691, 0.414254...  
1      [-0.044318266, 0.18805087, 0.11002458, 0.34255...  
2      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3      [-0.5569292, -0.17016356, -0.2739591, 0.464951...  
4      [-0.11862949, -0.33130506, -0.08209139, 0.5099...  
...                                                  ...  
44873  [-0.6082433, 0.13204779, -0.112084046, 0.63444...  
44874  [-0.9703356, 0.047477163, 0.04224369, 0.955539...  
44875  [-0.06892142, 0.095633335, -0.6287691, 0.70815...  
44876  [-0.7309477, -0.14236872, -0.22053114, 0.67461...  
44877  [-0.37761548, -0.339446, 0.09963914, 0.4470788...  

[44878 rows x 4 columns]

#TO CONVERT THE LIST OF STRINGS TO LISTS TO NUMBER(FLOAT)
def parse_vector(s):
    # Remove the leading/trailing brackets and any newlines
    clean = s.strip('[]').replace('\n', ' ')
    # Parse all whitespace‑separated floats into a 1D NumPy array
    return np.fromstring(clean, sep=' ')
data['vector'] = data['vector'].apply(parse_vector)
print(type(data.loc[0, 'vector']))        # should be <class 'numpy.ndarray'>
print(data.loc[0, 'vector'].shape)        # e.g. (100,)

In [29]:
data

text  class  \
0      nairobi reuters kenya s opposition leader rail...      1   
1      washington reuters the obama administration on...      1   
2                                                    NaN      0   
3      funny how this just keeps happeningyet another...      0   
4      helsinki reuters any move by finland to join n...      1   
...                                                  ...    ...   
44873  a gop lobbyist who s known for his own brand o...      0   
44874  washington reuters us president donald trump o...      1   
44875  washington reuters us president donald trump i...      1   
44876  in september stephen henderson the editorial e...      0   
44877  as said last year the russian hacking or russi...      0   

                                                  tokens  \
0      ['nairobi', 'reuters', 'kenya', 's', 'oppositi...   
1      ['washington', 'reuters', 'obama', 'administra...   
2                                                     []   
3      ['funny', 'keep', 'happeningyet', 'trump', 'ad...   
4      ['helsinki', 'reuters', 'finland', 'join', 'na...   
...                                                  ...   
44873  ['gop', 'lobbyist', 's', 'know', 'brand', 'big...   
44874  ['washington', 'reuters', 'president', 'donald...   
44875  ['washington', 'reuters', 'president', 'donald...   
44876  ['september', 'stephen', 'henderson', 'editori...   
44877  ['say', 'year', 'russian', 'hack', 'russiagate...   

                                                  vector  
0      [-0.2608485, -0.3120744, -0.22567691, 0.414254...  
1      [-0.04431827, 0.18805087, 0.11002458, 0.342555...  
2      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3      [-0.5569292, -0.17016356, -0.2739591, 0.464951...  
4      [-0.11862949, -0.33130506, -0.08209139, 0.5099...  
...                                                  ...  
44873  [-0.608243287, 0.132047787, -0.112084046, 0.63...  
44874  [-0.9703356, 0.04747716, 0.04224369, 0.9555391...  
44875  [-0.06892142, 0.09563334, -0.6287691, 0.708150...  
44876  [-0.7309477, -0.14236872, -0.22053114, 0.67461...  
44877  [-0.37761548, -0.339446, 0.09963914, 0.4470788...  

[44878 rows x 4 columns]

In [23]:
import pickle
#data.to_pickle("sentvect.pkl")

In [12]:
data = pd.read_pickle("sentvect.pkl")

MODEL TRAINING:- CLASSIFACATION MODEL

1. TRAIN-TEST SPLIT

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x= np.array(data["vector"].tolist())
y= data["class"].values
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [5]:
x

array([[-0.2608485 , -0.3120744 , -0.22567691, ..., -0.66506267,
         0.49639615, -0.34055185],
       [-0.04431827,  0.18805087,  0.11002458, ..., -0.07323468,
         0.00851312,  0.09037312],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.06892142,  0.09563334, -0.6287691 , ...,  0.40051186,
         0.450753  ,  0.5074561 ],
       [-0.7309477 , -0.14236872, -0.22053114, ...,  0.12037466,
         0.1400684 , -0.26194203],
       [-0.37761548, -0.339446  ,  0.09963914, ...,  0.02709828,
        -0.25618714, -0.5057525 ]])

In [6]:
x_train

array([[-0.03872294, -0.07082497, -0.4926529 , ..., -0.07860562,
         0.56346613,  0.1989021 ],
       [ 0.2402243 ,  0.05670504, -0.07572802, ..., -0.08809686,
         0.09194583,  0.0648774 ],
       [-0.65198016, -0.42665717, -0.06020387, ...,  0.20280705,
         0.26114944, -0.20901257],
       ...,
       [-0.8344815 , -0.1281819 ,  0.10502445, ...,  0.05037924,
        -0.28296283, -1.0847751 ],
       [-0.5752845 , -0.17587252, -0.27663207, ...,  0.19672608,
        -0.07173766, -0.31698188],
       [-0.19825898,  0.37413347,  0.12094874, ..., -0.36963648,
         0.26668528, -0.28186783]])

In [15]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(35902, 100) (35902,)
(8976, 100) (8976,)


2. APPLYING ML MODELS

* RANDOM FOREST

* Handles High Dimensional data.
* Reduces Overfitting and Biasness of the data.
* Ranks the features based on how useful they are for prediction.

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score

In [10]:
rf = RandomForestClassifier()

In [27]:
x_test

array([[ 1.0609524 , -0.00448151,  0.5738016 , ...,  0.07800025,
         0.11011701, -0.21875331],
       [ 0.3651273 , -0.11891536,  0.19727702, ..., -0.07260352,
         0.11422493,  0.11159955],
       [-0.32104307, -0.5377483 , -0.16249615, ..., -0.21382885,
         0.22556177, -0.25124916],
       ...,
       [-0.7372364 , -0.41424423, -0.36427706, ..., -0.10843354,
         0.14807628, -0.583819  ],
       [-0.75557178, -0.21877095, -0.03738625, ...,  0.11683361,
         0.10571497, -0.57505381],
       [-0.62836045, -0.17025669, -0.08447314, ...,  0.09682181,
         0.29064775, -0.11216603]])

In [11]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred_rf = rf.predict(x_test)

In [ ]:
y_pred_rf

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [ ]:
print("Accuracy: ",accuracy_score(y_test,y_pred_rf))

Accuracy:  0.9652406417112299


In [ ]:
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.96      0.97      0.97      4683
           1       0.97      0.96      0.96      4293

    accuracy                           0.97      8976
   macro avg       0.97      0.97      0.97      8976
weighted avg       0.97      0.97      0.97      8976



Decision Tree

In [4]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [18]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [19]:
y_pred_dt =dt.predict(x_test) 

In [20]:
y_pred_dt

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [22]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.92      0.93      0.93      4683
           1       0.93      0.91      0.92      4293

    accuracy                           0.92      8976
   macro avg       0.92      0.92      0.92      8976
weighted avg       0.92      0.92      0.92      8976



Logistic Regression

In [5]:
from sklearn.linear_model import LogisticRegression

In [25]:
lr = LogisticRegression()

In [26]:
lr.fit(x_train,y_train)

LogisticRegression()

In [28]:
y_pred_lr = lr.predict(x_test)

In [29]:
y_pred_lr

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [32]:
accuracy_score(y_test,y_pred_lr)

0.9745989304812834

ENSEMBLE VOTING

In [6]:
from sklearn.ensemble import VotingClassifier

In [7]:
classifiers = [('rf',RandomForestClassifier(random_state=1)),('dt',DecisionTreeClassifier(random_state=1)),('lr',LogisticRegression(max_iter=100,random_state=1))]

In [8]:
vc = VotingClassifier(estimators=classifiers,voting="hard")

In [19]:
model = vc.fit(x_train,y_train)

In [17]:
y_pred_vc = vc.predict(x_test)

In [18]:
print(classification_report(y_pred_vc,y_test))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      4687
           1       0.97      0.97      0.97      4289

    accuracy                           0.97      8976
   macro avg       0.97      0.97      0.97      8976
weighted avg       0.97      0.97      0.97      8976



In [24]:
pickle.dump(model,open("model.pkl","wb"))